# Student Performance Analytics System

A NumPy-based project to analyze student performance using data stored in a CSV file.

In [59]:
import os

print(os.getcwd())
print(os.listdir())

/content
['.config', 'students.csv', 'sample_data']


Import Libraries

In [41]:
import csv
import numpy as np

Create Dataset

In [42]:
# Student Performance Dataset
data = [
    ["Student_ID", "Maths", "Physics", "English", "Computer_Science"],
    [101, 85, 72, 90, 92],
    [102, 65, 88, 76, 70],
    [103, 92, 95, 89, 97],
    [104, 55, 61, 70, 58],
    [105, 78, 84, 82, 88]
]

# Create CSV file
with open("students.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerows(data)

print("students.csv created successfully!")

students.csv created successfully!


Load Dataset

In [43]:
# Load data from CSV file
students_data = np.loadtxt(
    "students.csv",
    delimiter=",",
    skiprows=1,
    dtype="int64"
)

# Subject names
subjects = np.array([
    "Maths",
    "Physics",
    "English",
    "Computer Science"
])

print("Dataset loaded successfully!")
print(students_data)

Dataset loaded successfully!
[[101  85  72  90  92]
 [102  65  88  76  70]
 [103  92  95  89  97]
 [104  55  61  70  58]
 [105  78  84  82  88]]


Understand the Dataset

In [44]:
# Get dataset information
total_students = students_data.shape[0]
total_subjects = students_data.shape[1] - 1

print("===== DATASET INFORMATION =====")

print(f"Number of students: {total_students}")
print(f"Number of subjects: {total_subjects}")
print(f"Total number of values: {students_data.size}")
print(f"Data type: {students_data.dtype}")

print(f"Student IDs: {students_data[:, 0]}")
print(f"Marks of Student 103: {students_data[2, 1:]}")
print(f"Maths marks: {students_data[:, 1]}")

===== DATASET INFORMATION =====
Number of students: 5
Number of subjects: 4
Total number of values: 25
Data type: int64
Student IDs: [101 102 103 104 105]
Marks of Student 103: [92 95 89 97]
Maths marks: [85 65 92 55 78]


Subject Analysis

In [45]:
# Select only subject marks
subject_marks = students_data[:, 1:]

# Calculate average of each subject
subject_average = np.mean(subject_marks, axis=0)

# Highest and lowest marks in the entire dataset
highest_marks = np.max(subject_marks)
lowest_marks = np.min(subject_marks)

# Highest and lowest marks for each subject
subject_highest_marks = np.max(subject_marks, axis=0)
subject_lowest_marks = np.min(subject_marks, axis=0)


print("===== SUBJECT ANALYSIS =====")

for i in range(total_subjects):
    print(
        f"{subjects[i]}: "
        f"Average = {subject_average[i]:.2f}, "
        f"Highest = {subject_highest_marks[i]}, "
        f"Lowest = {subject_lowest_marks[i]}"
    )

print(f"\nHighest mark in dataset: {highest_marks}")
print(f"Lowest mark in dataset: {lowest_marks}")

===== SUBJECT ANALYSIS =====
Maths: Average = 75.00, Highest = 92, Lowest = 55
Physics: Average = 80.00, Highest = 95, Lowest = 61
English: Average = 81.40, Highest = 90, Lowest = 70
Computer Science: Average = 81.00, Highest = 97, Lowest = 58

Highest mark in dataset: 97
Lowest mark in dataset: 55


Student Analysis

In [46]:
# Calculate average marks of each student
student_average = np.mean(subject_marks, axis=1)

# Find student with highest average
top_student_index = np.argmax(student_average)

top_student_id = students_data[top_student_index, 0]
top_student_average = student_average[top_student_index]


print("===== STUDENT ANALYSIS =====")

print("Average marks of all students:")

for i in range(total_students):
    print(
        f"Student {students_data[i, 0]}: "
        f"{student_average[i]:.2f}"
    )

print(
    f"\nTop Student: {top_student_id} "
    f"with an average of {top_student_average:.2f}"
)

===== STUDENT ANALYSIS =====
Average marks of all students:
Student 101: 84.75
Student 102: 74.75
Student 103: 93.25
Student 104: 61.00
Student 105: 83.00

Top Student: 103 with an average of 93.25


Pass / Fail Analysis

In [47]:
# Define pass mark
pass_mark = 70

# Create pass/fail mask
pass_mask = student_average >= pass_mark

# Count passed and failed students
passed_students = np.sum(pass_mask)
failed_students = total_students - passed_students

# Calculate pass percentage
pass_percentage = (passed_students / total_students) * 100

# Get IDs of failed students
fail_student_ids = students_data[~pass_mask, 0]


print("===== PASS / FAIL ANALYSIS =====")

print(f"Pass mark: {pass_mark}")
print(f"Students passed: {passed_students}")
print(f"Students failed: {failed_students}")
print(f"Pass percentage: {pass_percentage:.2f}%")
print(f"Failed student IDs: {fail_student_ids}")

===== PASS / FAIL ANALYSIS =====
Pass mark: 70
Students passed: 4
Students failed: 1
Pass percentage: 80.00%
Failed student IDs: [104]


Hardest Subject

In [48]:
# Find subject with lowest average
hardest_subject_index = np.argmin(subject_average)

hardest_subject = subjects[hardest_subject_index]
hardest_subject_average = subject_average[hardest_subject_index]


print("===== SUBJECT DIFFICULTY =====")

print(
    f"Hardest subject: {hardest_subject}"
)

print(
    f"Average marks: {hardest_subject_average:.2f}"
)

===== SUBJECT DIFFICULTY =====
Hardest subject: Maths
Average marks: 75.00


Student Consistency

In [49]:
# Calculate standard deviation for each student
student_std = np.std(subject_marks, axis=1)


print("===== STUDENT CONSISTENCY =====")

for i in range(total_students):
    print(
        f"Student {students_data[i, 0]}: "
        f"Standard Deviation = {student_std[i]:.2f}"
    )

===== STUDENT CONSISTENCY =====
Student 101: Standard Deviation = 7.79
Student 102: Standard Deviation = 8.58
Student 103: Standard Deviation = 3.03
Student 104: Standard Deviation = 5.61
Student 105: Standard Deviation = 3.61


Student Ranking

In [50]:
# Sort students based on average marks
ranking_indices = np.argsort(student_average)[::-1]

ranked_student_ids = students_data[ranking_indices, 0]
ranked_averages = student_average[ranking_indices]


print("===== STUDENT RANKING =====")

for i in range(total_students):
    print(
        f"{i + 1}. Student {ranked_student_ids[i]} "
        f"- Average: {ranked_averages[i]:.2f}"
    )

===== STUDENT RANKING =====
1. Student 103 - Average: 93.25
2. Student 101 - Average: 84.75
3. Student 105 - Average: 83.00
4. Student 102 - Average: 74.75
5. Student 104 - Average: 61.00


Final Summary

In [51]:
print("==========================================")
print("       STUDENT PERFORMANCE SUMMARY")
print("==========================================")

print(f"Total Students       : {total_students}")
print(f"Total Subjects       : {total_subjects}")
print(f"Top Student          : {top_student_id}")
print(f"Top Student Average  : {top_student_average:.2f}")
print(f"Students Passed      : {passed_students}")
print(f"Students Failed      : {failed_students}")
print(f"Pass Percentage      : {pass_percentage:.2f}%")
print(f"Hardest Subject      : {hardest_subject}")
print(f"Hardest Subject Avg  : {hardest_subject_average:.2f}")

print("==========================================")

       STUDENT PERFORMANCE SUMMARY
Total Students       : 5
Total Subjects       : 4
Top Student          : 103
Top Student Average  : 93.25
Students Passed      : 4
Students Failed      : 1
Pass Percentage      : 80.00%
Hardest Subject      : Maths
Hardest Subject Avg  : 75.00
